version: "3.8"
services:
  backend:
    build: ../pulseops-backend
    ports:
      - "5000:5000"
    networks:
      - pulseops-network
    
  frontend:
    build: ../pulseops-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - pulseops-network
networks:
  pulseops-network:
    driver: bridge